CREATE TABLE CLIENT(
    Client_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
     "NAME" VARCHAR(30), ADDRESS VARCHAR(30), CITY VARCHAR(25),
"STATE" CHAR(2), PHONE CHAR(12), EMAIL VARCHAR(40), CREDIT_CARD VARCHAR(20), DNI VARCHAR(9));

CREATE TABLE PURCHASE (
PURCHASE_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
ORDER_NUM INTEGER NOT NULL,
CLIENT_ID INTEGER NOT NULL,
PRODUCT_ID INTEGERx NOT NULL,
QUANTITY SMALLINT,
SHIPPING_COST DECIMAL(12, 2),
SALES_DATE DATE,
SHIPPING_DATE DATE,
FREIGHT_COMPANY VARCHAR(30));

ALTER TABLE PURCHASE
ADD FOREIGN KEY ( Client_ID)
REFERENCES  Client(Client_ID)

ALTER TABLE PURCHASE
ADD FOREIGN KEY ( PRODUCT_ID)
REFERENCES  PRODUCT(PRODUCT_ID)

-- hacer un join
select CLIENT."NAME",PRODUCT.DESCRIPTION,PRODUCT.PURCHASE_COST ,PURCHASE.SALES_DATE
from APP.PURCHASE inner join APP.CLIENT on PURCHASE.CLIENT_ID=CLIENT.CLIENT_ID
inner join APP.PRODUCT on PURCHASE.PRODUCT_ID=PRODUCT.PRODUCT_ID
where CLIENT.CLIENT_ID=6
